[package]
name = "substrate-remote-sign-server"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
publish = false
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
description = "This is an example application for the JSON-RPC Substrate Simple Remote Signer protocol."
homepage = "https://substrate.dev"
repository = "https://github.com/paritytech/substrate/"

[dependencies]
sc-remote-signer = { package = "sc-jsonrpc-remote-signer", version = "0.8.0", path = "../../../client/jsonrpc-remote-signer" }
structopt = { version = "0.3", default-features = false }
sc-cli = { version = "0.8.0", path = "../../../client/cli" }
sc-keystore = { version = "2.0.0", path = "../../../client/keystore" }
sc-service = { version = "0.8.0", path = "../../../client/service" }
jsonrpc-http-server = { version = "14.2.0" }
jsonrpc-ws-server = { version = "14.2.0" }
tokio = { version = "0.2", features = ["full"] }
env_logger = "0.7.1"