[package]
name = "substrate-remote-sign-server"
version = "0.1.0"
authors = ["Benjamin Kampmann <ben@parity.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sc-remote-signer = { package = "sc-jsonrpc-remote-signer", version = "2.0.0-rc6", path = "../../../client/jsonrpc-remote-signer" }
structopt = { version = "0.3", default-features = false }
sc-cli = { version = "0.8.0-rc6", path = "../../../client/cli" }
sc-keystore = { version = "2.0.0-rc6", path = "../../../client/keystore" }
sc-service = { version = "0.8.0-rc6", path = "../../../client/service" }
jsonrpc-http-server = { version = "14.2.0" }
jsonrpc-ws-server = { version = "14.2.0" }
tokio = { version = "0.2", features = ["full"] }
env_logger = "0.7.1"